# Generated by Django 4.1.7 on 2023-03-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesbill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_bill',
            name='amount_in_kg',
        ),
        migrations.AddField(
            model_name='sales_bill',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
