# Generated by Django 4.1.7 on 2023-03-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPriceOrPercentageDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(choices=[('percentage', 'percentage'), ('price', 'price')], max_length=20)),
                ('percentage', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowPriceOrPercentageIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(choices=[('percentage', 'percentage'), ('price', 'price')], max_length=20)),
                ('percentage', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('in_stock', models.IntegerField()),
                ('sale_unit', models.CharField(choices=[('Pcs', 'Pcs'), ('Kg', 'Kg'), ('Dozn', 'Dozn'), ('6Pcs', '6Pcs')], default='Pcs', max_length=20)),
                ('our_rate', models.FloatField()),
                ('rate', models.FloatField()),
                ('import_date', models.DateField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.showpriceorpercentagediscount')),
                ('increment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.showpriceorpercentageincrement')),
            ],
        ),
    ]
