# Generated by Django 4.1.7 on 2023-03-19 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.showpriceorpercentagediscount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='increment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.showpriceorpercentageincrement'),
        ),
    ]
