# Generated by Django 4.1.7 on 2023-03-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_discount_alter_product_increment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_unit',
            new_name='sales_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='increment',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='increment_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='increment_rate',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='ShowPriceOrPercentageDiscount',
        ),
        migrations.DeleteModel(
            name='ShowPriceOrPercentageIncrement',
        ),
    ]
