# Generated by Django 4.1.7 on 2023-03-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_sale_unit_product_sales_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='our_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
