# Generated by Django 4.1.7 on 2023-03-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='import_date',
        ),
    ]
