# Generated by Django 4.1.7 on 2023-03-21 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_import_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='latest_bill_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 9, 17, 38, 619093)),
        ),
        migrations.AddField(
            model_name='product',
            name='latest_bill_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='our_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
