# Generated by Django 4.1.7 on 2023-03-21 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_discount_percentage_product_discount_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='latest_bill_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
