# Generated by Django 4.1.7 on 2023-03-21 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_latest_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='latest_bill_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
