# Generated by Django 4.1.7 on 2023-03-21 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_latest_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='latest_bill_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
