# Generated by Django 4.1.7 on 2023-03-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_latest_bill_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='latest_bill_id',
        ),
    ]
