# Generated by Django 4.1.7 on 2023-03-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_latest_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latest_bill_id',
            field=models.IntegerField(default=1),
        ),
    ]
