# Generated by Django 4.1.7 on 2023-03-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_rename_sale_unit_product_sales_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_kg', models.FloatField(blank=True, null=True)),
                ('amount_in_pcs', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('discount_percentage', models.FloatField()),
                ('discount_rate', models.FloatField()),
                ('rate', models.FloatField()),
                ('import_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
