# Generated by Django 4.1.7 on 2023-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importbill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_bill',
            name='our_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
