# Generated by Django 4.1.7 on 2023-03-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importbill', '0002_import_bill_our_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_bill',
            name='latest_bill_id',
            field=models.IntegerField(default=1),
        ),
    ]
