# Generated by Django 4.1.7 on 2023-03-24 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importbill', '0003_import_bill_latest_bill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import_bill',
            name='latest_bill_id',
        ),
    ]
